definitions:
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      password:
        type: string
      role_id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  role.CreateRoleRequest:
    properties:
      permission:
        example: full_access
        type: string
      username:
        example: admin
        type: string
    required:
    - username
    type: object
  role.RoleErrorResponse:
    properties:
      details:
        example: status bad request
        type: string
      message:
        example: status bad request
        type: string
    type: object
  role.RoleSuccessResponse:
    properties:
      created_at:
        example: "2025-01-01T00:00:00Z"
        type: string
      id:
        example: 1
        type: integer
      permission:
        example: full_access
        type: string
      updated_at:
        example: "2025-01-01T01:00:00Z"
        type: string
      username:
        example: Beslan
        type: string
    type: object
  user.CreateUserRequest:
    properties:
      email:
        example: ivan@example.com
        type: string
      password:
        example: secret
        type: string
      role_id:
        example: 1
        type: integer
      username:
        example: ivan
        type: string
    required:
    - email
    - password
    - username
    type: object
  user.UserCreatedResponse:
    properties:
      id:
        example: 1
        type: integer
    type: object
  user.UserErrorResponse:
    properties:
      details:
        example: status bad request
        type: string
      message:
        example: status bad request
        type: string
    type: object
  user.UserInternalErrorResponse:
    properties:
      message:
        example: internal server error
        type: string
    type: object
  user.UserNotFoundResponse:
    properties:
      message:
        example: user not found
        type: string
    type: object
  user.UserSuccessResponse:
    properties:
      created_at:
        example: "2025-01-01T00:00:00Z"
        type: string
      email:
        example: dudaev.beslan@bk.ru
        type: string
      id:
        example: 1
        type: integer
      is_active:
        example: true
        type: boolean
      role_id:
        example: 1
        type: integer
      updated_at:
        example: "2025-01-01T01:00:00Z"
        type: string
      username:
        example: beslan
        type: string
    type: object
info:
  contact: {}
paths:
  /roles:
    delete:
      consumes:
      - application/json
      description: Delete role
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/role.RoleSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/role.RoleErrorResponse'
      summary: Delete role
      tags:
      - roles
    get:
      consumes:
      - application/json
      description: Get roles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/role.RoleSuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/role.RoleErrorResponse'
      summary: GetAll roles
      tags:
      - roles
    post:
      consumes:
      - application/json
      description: Create a new role
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/role.CreateRoleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/role.RoleSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/role.RoleErrorResponse'
      summary: Create role
      tags:
      - roles
    put:
      consumes:
      - application/json
      description: Update role
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/role.RoleSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/role.RoleErrorResponse'
      summary: Update role
      tags:
      - roles
  /roles/{id}:
    get:
      consumes:
      - application/json
      description: Get role by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/role.RoleSuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/role.RoleErrorResponse'
      summary: GetByID role
      tags:
      - roles
  /users:
    delete:
      consumes:
      - application/json
      description: Get user details by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.UserErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/user.UserNotFoundResponse'
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/user.UserInternalErrorResponse'
      summary: Get user by ID
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.UserCreatedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.UserErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/user.UserNotFoundResponse'
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/user.UserInternalErrorResponse'
      summary: Create user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Get user details by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.UserErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/user.UserNotFoundResponse'
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/user.UserInternalErrorResponse'
      summary: Get user by ID
      tags:
      - users
  /users/:
    get:
      consumes:
      - application/json
      description: Get user details by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.UserErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/user.UserNotFoundResponse'
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/user.UserInternalErrorResponse'
      summary: Get user by ID
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get user details by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/user.UserErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/user.UserNotFoundResponse'
        "501":
          description: Not Implemented
          schema:
            $ref: '#/definitions/user.UserInternalErrorResponse'
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
